### ISSUE TITLE
USB output on other consoles

### ISSUE THREAD

**Issue by Invictaz** [sonik-br/lgff_wheel_adapter#3]
Is it also possible to do USB output e.g. to Sony Playstation Classic or other console that accepts USB?

**Comment by sonik-br** [comment]
It's possible but it's not in the scope of this project.
The PS Classic supports analog controllers? Or just digital?

**Comment by Invictaz** [comment]
@sonik-br Analog also, normally via 8bitdo Adapter 2 (e.g. Gran Turismo games).
The only solution for now would be GIMX but I think not a lot of people have tried. 
Another option would be CronusMax via Xinput and a PC that can translate the wheel to CronusMax but the CronusPro software only accepts a couple of wheels I think.

There is also the Brook Wingman USB but it's quite locked. It doesn't support a lot of wheels and the micro USB output doesn't do analog, so you need a PSX to USB converter cable to spoof it, thinking it is connected to a Playstation.

**Comment by sonik-br** [comment]
I don't any of those adapters to see how they output analog mode. Plus I also don't have a PS Classic.

**Comment by Invictaz** [comment]
PS Classic is an example. Playstation 3 or Nintendo Swith does accept USB input natively without encryption. Nintendo Wii does it via Fakemote and Nintendo WiiU via HID2VPAD (both when emulating a PS3 Dualshock 3).

**Comment by sonik-br** [comment]
The adapter can already output as a Driving Force Pro.
But even a real driving force pro is not a dualshock. Only compatible games supports it.
What you want is to output as a dualshock 3 controller.

This is out of scope and I don't have any plans to implement this.
But I'm also working on some other adapters and I might do this in one of them in the future.

**Comment by Invictaz** [comment]
Yes we have the project you mention https://github.com/mathijsvandenberg/g29emu this would be good for the Pico. I do not have an Arduino.

**Comment by Invictaz** [comment]
For Playstation 2 output and wheel emulation you might want to look at 

https://github.com/jackun/USBqemu-wheel/tree/master

**Comment by sonik-br** [comment]
The adapter already works on PS2 via USB

**Comment by Invictaz** [comment]
I hope you can add Nintendo Switch output since this project is incomplete

https://github.com/PieroBarcellos/sys-con

**Comment by sonik-br** [comment]
AFAIK Switch does not have a real spec for wheels. Wheels reports as a common gamepad and the mapping vary from game to game.
Adding support for it will require a way to remap the output buttons on the firmware.
It's not on my roadmap but should be easy to add if anyone wants.

**Comment by Invictaz** [comment]
You can map controls in the Nintendo Switch menu.

Also, most wheels are secretly controllers. One user investigated the offical Mario wheel on Switch made by Hori and it is a Switch pro controller having the right stick set to dead zone 100. See here for his developments.

https://gbatemp.net/threads/logitech-g920-on-switch.622575/post-10028114

**Comment by sonik-br** [comment]
Yeah that's what I mean. Most (or all) switch devices shares the same gamepad report.
Good point on the remap. But it requires the device to emulate the Switch Pro controller. It's protocol is more complex if anyone is going to implement.

**Comment by Invictaz** [comment]
From seeing your Xbox code this is also the case on XID. The wheel is mapped as a controller. 

For Switch you can use the Hori Pad S. The Cronus Zen emulates that if you choose Switch output. It might be easier than the Switch Pro. However, the Switch pro is also documented. Only the NFC scanner isn't very in detail.

**Comment by Invictaz** [comment]
Did you look at GIMX emups3 for the Playstation 3?

https://github.com/matlo/GIMX-firmwares/blob/master/EMUPS3/emu.c

There is also a plugin on the ps3 side but the source is outdated (only 0.4 source available while the version is 0.8)

https://consolemods.org/wiki/PS3:PS3XPAD

There is some newer project

https://github.com/geniass/ps3steampad

Ps3 has quite a lot of racing games but no developments for older wheels. Only G25 and G27 support.

**Comment by sonik-br** [comment]
My usb output is based on GIMX.
The firmware can already emulate a lot of logitech wheels. Should cover all games on ps3 that supports a logitech ffb wheel.
What I'm not going to do is to output as a dualshock / common controller.

**Comment by Invictaz** [comment]
So it already does PS3 output you say?

**Comment by sonik-br** [comment]
Yes. The purpose of the adapter is to make some wheels compatible with PS2 and PS3.
Most logitech ffb wheels are already compatible with PS3.
But the adapter can help if the ps3 does not have native support for it.

**Comment by Invictaz** [comment]
It might be possible to use it on the PS4 too. After 2016 the authentication controller (usually after 8 mins a key is requested) was removed.

From Drivehub manual

![Screenshot_20240301_215859_Samsung Notes](https://github.com/sonik-br/lgff_wheel_adapter/assets/20338545/d9e4338e-4fd8-4557-a89e-311dc76d515f)

**Comment by Invictaz** [comment]
> My usb output is based on GIMX. The firmware can already emulate a lot of logitech wheels. Should cover all games on ps3 that supports a logitech ffb wheel. What I'm not going to do is to output as a dualshock / common controller.

I investigated further. Even the Ras1ution 2 a 130 dollar wheel adapter outputs as a Switch controller

![Screenshot_20240301_220849_Samsung Notes](https://github.com/sonik-br/lgff_wheel_adapter/assets/20338545/b11939f6-f9a4-43c6-b89b-05585b4c14a1)

**Comment by sonik-br** [comment]
Authentication was not removed on PS4.

And I agree that various adapters are compatible with Switch. It's a 130 dollar adapter. Mine is free for anyone to use, fork, add more features.

**Comment by Invictaz** [comment]
> Authentication was not removed on PS4.
> 
> And I agree that various adapters are compatible with Switch. It's a 130 dollar adapter. Mine is free for anyone to use, fork, add more features.

Huh, why does Drivehub say that for wheels in its manual then?

Let's make the 5 dollar adapter software that the expensive is not needed anymore haha.

**Comment by sonik-br** [comment]
I'm not sure what is Direct Drive but it's not authentication.

**Comment by Invictaz** [comment]
Direct Drive is just the controller into the hub and no authentication controller. See the manual.

**Comment by sonik-br** [comment]
Ok, but I don't get why auth was removed and how it affects Fanatec devices.
What makes more sense to me would be if auth was not required for some wheels before 2016.
And Direct Drive is only available for Fanatec devices?

On a side note, I've never seen a fanatec wheel before. I don't have access to any and support for them will simply not happen.

**Comment by Invictaz** [comment]
Sony required game developers to remove the whitelist of only allowed wheels. After that Date more wheels could work on various games. The Drivehub made these wheels work on older games. That is how I read it.

**Comment by sonik-br** [comment]
Closing as it's out of the scope of the project.
