### ISSUE TITLE
Playstation 2 plug output

### ISSUE THREAD

**Issue by Invictaz** [sonik-br/lgff_wheel_adapter#4]
Maybe try to have Playstation 2 plug output since not all games recognize wheels via USB?

https://github.com/luisibalaz/pico2ds2

**Comment by sonik-br** [comment]
Like I said, this is not the scope of this project.
Plus the linked project only emulates a digital pad. And there's no source code shared.

**Comment by Invictaz** [comment]
@sonik-br the source is just an example. I simply googled for a couple of minutes. Needs more investigation.
