### ISSUE TITLE
Wii and gamecube output

### ISSUE THREAD

**Issue by Invictaz** [sonik-br/lgff_wheel_adapter#5]
Hey I saw on your Twitter/X post that you are investigating Wii and Gamecube output.

Did you check out [Fakemote](https://github.com/xerpi/fakemote/) and [Nintendont] (https://github.com/FIX94/Nintendont) ?

The latter has support for ini files. So if you would design a pico firmware that outputs as a wii or gamecube wheel we might are able to write an ini file that Nintendont understands to have working in Gamecube games on Wii and WiiU.

Andother finding is [HID2VPad](https://github.com/Maschell/hid_to_vpad) which recently got a port to the Aroma environment. If you write an ini file for it it can be used.

I'm not sure how the Gamecube and Wii wheels work. Do they output as a Wiimote with nunchuck for the axis or on the Gamecube side do they output as a controller?

**Comment by sonik-br** [comment]
I need access to those devices to see how they work. Never seen they before.

**Comment by Invictaz** [comment]
I have the Wii and WiiU so I can check.

**Comment by Invictaz** [comment]
Isn't the Wii Wheel data in the new-lg4ff repo?

![image](https://github.com/sonik-br/lgff_wheel_adapter/assets/20338545/4bb70d8d-6e3e-424f-a33b-613a861dcf38)

**Comment by Invictaz** [comment]
See 

https://wiibrew.org/wiki/Logitech_USB_steering_wheel

**Comment by Invictaz** [comment]
The gamecube wheel is made by Immersion technologies

I guess you can use this driver https://github.com/timschumi/iforce-binary-driver

Most Logitech Wheels use the Immersion technology as base.

https://i.ebayimg.com/images/g/KGsAAOSwCLpk5ogV/s-l1600.png

**Comment by Invictaz** [comment]
List of Gamecube games that support the Wheel

4x4 Evolution 2
Burnout 2: Point of Impact
Dakar 2: The World's Ultimate Rally
F-Zero GX
Hot Wheels: Velocity X
Mario Kart Double Dash
NASCAR HEAT 2: Dirt to Daytona
NASCAR Thunder
NASCAR Thunder 2003
Need For Speed Underground
Need For Speed Underground 2
Need For Speed:Hot Pursuit 2
PRO RALLY 2002
R: Racing Evolution
Rally Championship
Street Racing Syndicate
The Simpsons Hit & Run
V-Rally 3
Starsky & Hutch

**Comment by Invictaz** [comment]
You also have the Logic3 NW819 wheel for Wii

![image](https://github.com/sonik-br/lgff_wheel_adapter/assets/20338545/dc91d88c-6b07-4320-b515-2cac49dfdbff)

**Comment by Invictaz** [comment]
Gamecube compatible wheels

madcatz mc2
saitek gtz500
thrustmaster universal challenge
thrustmaster kart challenge
thrustmaster challenge 2
Intec Racing wheel

**Comment by sonik-br** [comment]
> Isn't the Wii Wheel data in the new-lg4ff repo?
> 
> You don't need the wheel. It connects via a wireless adapter that you put in the Wii USB port
> 

Handy to have access to one to do a testing but yes it might be possible to do with the info on that page.

The GC one does not seem to use the exact same commands as other logitech wheels.
Dolphin only handles the Constant effect and transtates it to dinput.

**Comment by Invictaz** [comment]
> > Isn't the Wii Wheel data in the new-lg4ff repo?
> > You don't need the wheel. It connects via a wireless adapter that you put in the Wii USB port
> 
> Handy to have access to one to do a testing but yes it might be possible to do with the info on that page.
> 
> The GC one does not seem to use the exact same commands as other logitech wheels. Dolphin only handles the Constant effect and transtates it to dinput.

You mean this file?

https://github.com/dolphin-emu/dolphin/blob/5090a028e6e4125b780bcb1c76dcd8fe956a0b97/Source/Core/Core/HW/SI/SI_DeviceGCSteeringWheel.cpp#L4

https://github.com/NicoHood/Nintendo/commit/ba9816c347ca142030281063487fe8ca9e2137ba

**Comment by Invictaz** [comment]
It seems on some games the degrees of rotation must be set even lower than 270 degrees

https://soloemulacion.blogspot.com/2014/06/guia-analisis-usando-un-volante-en.html

**Comment by Invictaz** [comment]
> Can you dump the usb data for the wii wheel? Gamecube will be more complex as you will need to build a hardware to talk to the device.

I do have the WUP-028 Gamecube to USB adapter but no driver for it and I don't have the Gamecube Wheel.

**Comment by sonik-br** [comment]
I'm not sure if a gneric gamecube to usb adapter would help in this case.
I can read a gamecube device via arduino or pico but I don't have the wheel. Let's see if I can get one.

**Comment by Invictaz** [comment]
> I'm not sure if a gneric gamecube to usb adapter would help in this case. I can read a gamecube device via arduino or pico but I don't have the wheel. Let's see if I can get one.

This is the official Nintendo adapter

![image](https://github.com/sonik-br/lgff_wheel_adapter/assets/20338545/7c69ec98-c119-4f22-af0b-c2608d45b1d5)

**Comment by sonik-br** [comment]
The adapter is not made for wheel devices. I'm pretty sure that it will not pass force feedback commands.

**Comment by Invictaz** [comment]
The joybus protocol doesn't have a lot of options and this adapter has 2 USB port, one specially for rumble as it requires additionele power. Who says rumble isn't broadcasted over the forcefeedback lines anyway?

The only other option is this

https://www.amazon.com/Nyko-Retro-Controller-Adapter-GameCube-Nintendo/dp/B07JGH2645?th=1

Or the Mayflash adapter.

**Comment by Invictaz** [comment]
046D:C29C=Speed Force Wireless Wheel for Wii
046D:CAB1=Cordless Keyboard for Wii HID Receiver

**Comment by Invictaz** [comment]
Sadly Logitech doesn't describe the protocol in their pdf. Not even in v1.0. Must be because on older wheels they licensed it from Immersion so it isn't their own protocol.

https://github.com/mathijsvandenberg/g29emu/files/14395098/Logitech_Force_Feedback_Protocol_V1.6.pdf

**Comment by Invictaz** [comment]
The C-X5A57 adapter dongle for the Wii Wheel is 10USD on Ebay. It is also used by the wireless Playstation 3 wheel and the Cordless precision controller.

![c1823c1e-bd0f-4667-a096-0382a15b5de9](https://github.com/sonik-br/lgff_wheel_adapter/assets/20338545/476f3c3d-7fa9-49a9-bf47-547309173f35)

**Comment by sonik-br** [comment]
Interesting! So same dongle for multiple devices.
I bet that it does change it's ID based on the paired device.

Btw ebay does not help. I live in Brazil. Most stuff on ebay does not ship there, or the shipping value plus import tax would be a deal breaker. And if it needs the wheel to work, I would also need the wheel :/

**Comment by Invictaz** [comment]
I see on X you need the pedal output on the Gamecube. From what I asked around on various Discord servers the Wii games had specific powerpc code to address the wireless adapter. It is rumored that to have wheel support you need assistance from Nintendo. But not sure.

**Comment by sonik-br** [comment]
This is for the wii, right? I don't have that wheel.
I'm looking into how it the wiring of the GC pedal.

**Comment by Invictaz** [comment]
I think the Wii side of things will be much more difficult than the Gamecube for now. But I need to see in the SDK.

**Comment by sonik-br** [comment]
By looking at the Dolphin code, the GC wheel only seems to support the Constant effect. Or at least that's what Fzero uses. Can't find logs from other games. So GC should be easy to implement as adedicated adapter. Mapping other effects to it will be difficult.

Wii on the other hand seems to use the same ffb commands as other logitech wheels. I hope o get one to do some tests.

**Comment by sonik-br** [comment]
Closing as it's out of the scope of the project.
Gamecube does not use usb, plus I think the wheel only have simple constant effect. It does not share the same ffb protocol as other logitech wheels.

Wii (speed force wireless) input/output might happen in the future if I can get one.
